// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//import 'firebase_options.dart';
/// // ...
//await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
//);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJK-SlI6_hPBU5X9WsbhJpxwgcjBfdgEE',
    appId: '1:299664269818:web:71975d975dfb94f7384443',
    messagingSenderId: '299664269818',
    projectId: 'digital-navigator-94f33',
    authDomain: 'digital-navigator-94f33.firebaseapp.com',
    storageBucket: 'digital-navigator-94f33.firebasestorage.app',
    measurementId: 'G-7S8RQ4XEM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8F8r0MmyI2wdfeczR_oRggCvQZQk1-0A',
    appId: '1:299664269818:android:2bc7ad57caa62a7b384443',
    messagingSenderId: '299664269818',
    projectId: 'digital-navigator-94f33',
    storageBucket: 'digital-navigator-94f33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo9fQzaRlAflDMAXTRqUClbxGucwJO46k',
    appId: '1:299664269818:ios:68d5f3f3c624a800384443',
    messagingSenderId: '299664269818',
    projectId: 'digital-navigator-94f33',
    storageBucket: 'digital-navigator-94f33.firebasestorage.app',
    iosBundleId: 'com.G06.digitalNavigator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo9fQzaRlAflDMAXTRqUClbxGucwJO46k',
    appId: '1:299664269818:ios:68d5f3f3c624a800384443',
    messagingSenderId: '299664269818',
    projectId: 'digital-navigator-94f33',
    storageBucket: 'digital-navigator-94f33.firebasestorage.app',
    iosBundleId: 'com.G06.digitalNavigator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJK-SlI6_hPBU5X9WsbhJpxwgcjBfdgEE',
    appId: '1:299664269818:web:0451c341a4d083d9384443',
    messagingSenderId: '299664269818',
    projectId: 'digital-navigator-94f33',
    authDomain: 'digital-navigator-94f33.firebaseapp.com',
    storageBucket: 'digital-navigator-94f33.firebasestorage.app',
    measurementId: 'G-ZZH05SF29H',
  );
}
